---
title: "CV"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cosmo
---

## Education

07/2024 - Present 

**Columbia University Mailman School of Public Health** 

MS in Patient Oriented Research, to be completed in June 2025

07/2016 - 06 /2020

**Icahn School of Medicine at Mount Sinai**

MD, with Distinction in Research

---

## Academic Appointments
07/2024 - Present

**Department of Medicine, Division of Gastroenterology, New York Presbyterian-Columbia University Medical Center**

NIH/NIDDK T32 Postdoctoral Fellow


07/2020 - 06/2023

**Department of Medicine, Icahn School of Medicine at Mount Sinai**

Resident

---


## Board Certification

Board Certified in Internal Medicine

---

## Academic Service

2024 - Present

Trainee Associate Member for the Herbert Irving Comprehensive Cancer Center

2024 - Present

Research Conference Fellow for the Division of Gastroenterology at the New York Presbyterian-Columbia 
University

2022 - 2023

Liver Rotation Representative for Internal Medicine House Staff at Icahn School of Medicine at Mount	Sinai

---

## Professional Organizations and Societies

* American Gastroenterology Association, Member 
* American Society for Gastrointestinal Endoscopy, Member 
* American College of Gastroenterology, Member 
* American Medical Association, Member 
* Sigma Xi The Scientific Research Honor Society, Associate Member
* Journal Reviewer: JAMA Network Open

---

## Grant Support
<u>Current Support</u>

<u>7/2024 – Present</u>

NIH/NIDDK T32 (2T32DK083256-16) Multidiscplinary Training in Translational Gastrointestinal and Liver Research (PI: Timothy C. Wang)


<u>Past Support</u>

<u>2017 - 8/2017</u>

Icahn School of Medicine Summer Student Investigator Award (PI – Michelle K. Kim, MD, PhD)

Prognostic validity of the American Joint Committee on Cancer staging criteria for midgut neuroendocrine tumors

Role: Student Investigator

<u>6/2015 - 8/2015</u>

Chemistry of Life Processes Summer Scholar Award (PI – Thomas V. O’Halloran, PhD)

Novel microtubule-binding anti-cancer compound induces apoptosis of U87 glioblastoma multiforme via hyperploidy and cell cycle arrest

Role: Chemistry of Life Processes Summer Scholar

<u>6/2014 - 8/2014</u>

Northwestern University Summer Undergraduate Research Grant $3,000	(PI – Thomas V. O’Halloran, PhD)

Evaluation of novel nanobins with arsenic and cisplatin for targeted drug delivery

Role: Student Investigator


<u>11/2013 - 11/2013</u>

Avon Foundation Scholarship for Conference Travel (PI – Balaji Sitharaman, PhD)

Toward treatment of breast cancer using graphene- and carbon-based nanoparticles as drug delivery and hyperthermia agents

Role: Student Investigator

<u>6/2011 - 9/2012</u>

Students & Scientists United for Breast Cancer Prevention Research (PI – Balaji Sitharaman, PhD)

Toward graphene-based imaging and drug-delivery agents for breast cancer: cytotoxicity of graphene oxide nanoribbons in human breast cancer cell lines

Role: Student Investigator

