---
title: "Publications"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cosmo
---

# Select Publications

Wang CP, McKinley M, Vu A , **Yang JY**, Gupta S, Gomez SL, Kim MK, Itzkowitz SH, Shah SC. Demographic comparison of the burden of endoscopically screenable cancers in the United States. Gastro Hep Advances 2024. DOI: https://doi.org/10.1016/j.gastha.2024.01.005.

Holmer AK, Luo J, Russ KB, Park S, **Yang JY**, Ertem F, Dueker J, Nguyen V, Hong S, Zenger C, Axelrad JE, Sofia A, Petrov JC, Al-Bawardy B, Fudman DI, Llano E, Dailey J, Jangi S, Khakoo N, Damas OM, Barnes EL, Scott FI, Ungaro RC, Singh S; REACH-IBD (Rising Educators Academics and Clinicians Helping-IBD). Comparative Safety of Biologic Agents in Patients with Inflammatory Bowel Disease with Active or Recent Malignancy: A Multi-Center Cohort Study. Clin Gastroenterol Hepatol. 2023 Jan 12:S1542-3565(23)00029-0. doi: 10.1016/j.cgh.2023.01.002. Epub ahead of print. PMID: 36642291.

Nasser Y, Biala S, Chau M, Partridge AC, **Yang JY**, Lethebe BC, Stinton LM, Cooray M, Cole M, Ma C, Chen Y, Andrews CN, Forbes N. Baseline cannabinoid use is associated with increased sedation requirements for outpatient endoscopy. Cannabis Cannabinoid Res. 2022 Oct 20. doi: 10.1089/can.2022.0203. Epub ahead of print. PMID: 36269560.

**Yang JY**, Baeg K, Martin JA, Wisnivesky J, Kim MK. Assessing the prognostic validity of the American Joint Committee on Cancer staging classification for midgut neuroendocrine tumors. Pancreas 2021;50(10):e81-e82. DOI: 10.1097/mpa.0000000000001938.

Aroniadis OC, Wang X, Gong T, Forbes N, **Yang JY**, Canakis A, Elmunzer BJ, Yadav D. Factors associated with the development of gastrointestinal symptoms in patients hospitalized with COVID-19. Digestive Diseases and Sciences 2021. DOI: 10.1007/s10620-021-07286-7.

Rabinowitz LG, Zylberberg HM, **Yang JY**, Gold SL, Chesner J, Ji J, Hu L, Dubinsky M. De Novo Ostomy Placement Is Associated with Increased Outpatient Opioid Use In Patients with Inflammatory Bowel Disease. Digestive Diseases and Sciences. 2021. DOI: 10.1007/s10620-021-07257-y.

Ni K, **Yang JY**, Baeg K, Leiter AC, Mhango G, Gallagher EJ, Wisnivesky JP, Kim MK. Association between somatostatin analogues and diabetes mellitus in gastroenteropancreatic neuroendocrine tumor patients: A Surveillance, Epidemiology, and End Results-Medicare analysis of 5235 patients. Cancer reports (Hoboken, NJ). 2021:e1387.

**Yang JY**, Parkins MD, Canakis A, Aroniadis OC, Yadav D, Dixon RE, Elmunzer BJ, Forbes N. Outcomes of COVID-19 Among Hospitalized Health Care Workers in North America. JAMA Netw Open. 2021 Jan 4;4(1):e2035699. doi: 10.1001/jamanetworkopen.2020.35699.

Rustgi SD, Oh A, **Yang JY**, Kang D, Wolin E, Kong CY, Hur C, Kim MK. Initiation of Somatostatin analogues for neuroendocrine tumor patients: a cost-effectiveness analysis. BMC Cancer 2021;21(1):597. DOI: 10.1186/s12885-021-08306-5.

Elmunzer BJ, Wolf BJ, Scheiman JM, Tierney WM, Taylor JR, Merchant AA, Patel VA, Willingham FF, Howard EF, West MK, Koza CL, Yachimski PS, Qayed E, Nustas R, Zakaria A, Piper MS, Jaza L, Forbes N, Chau M, Lara LF, Papachristou GI, Okafor U, Conwell DL, Volk ML, Mosier E, Azab M, Patel A, Hilson LG, Zhou S, Buxbaum J, Kushnir VM, Lenyo AM, Sloan IP, Hollander T, McLeod CG, Spitzer RL, Wakefield L, Nitchie H, Ordiah CO, Rockey DC, Alford TB, Amin S, Kuftinec G, Deshpande AR, Yadav D, Saul M, Mays M, Anderson G, Wood K, Mathews L, Fox C, Kolb JM, Wani S, Pawa S, Pawa R, Canakis A, Huang C, Jamil LH, Aneese AM, Gjeorgjievski VM, Imam Z, Odish F, Edhi AI, Orosey M, Tiwari A, Patwardhan S, Glamour BK, Smith ZL, Hosmer AE, Furey N, Xhak A, Hanley KA, Wood J, Keswani RN, Patel HK, Shah JN, Agarunov E, Brown NG, Patel AA, Sethi A, Fogel EL, McNulty G, Haseeb A, Trieu JA, Dixon RE, **Yang JY**, DiMaio CJ, Mendelsohn RB, Calo D, Aroniadis OC, LaComb JF, Cruz L, Reykhart O, Sauer BG, Diakova G, Dang DT, Piraka CR, Shah ED, Caisse M, Zbib NH, Damianos JA, Pohl H, Mitchell S, Bronze MS, Condon A, Lenhart A, Muthusamy R, Dua KS, Kanagala VS, Esteban J, Jamal A, Canto MI, Singh VK, Pinto-Sanchez MI, Hutchinson JM, Kwon RS, Korsnes SJ, Waljee AK, Tang W, Zhang Y, Zhu J, Singh H, Solati Z, Hajidiacos. Association Between Preadmission Acid Suppressive Medication Exposure and Severity of Illness in Patients Hospitalized With COVID-19. Gastroenterology. 2021;160(4):1417-1422.e1414.

Pan D, Ip A, Zhan S, Wasserman I, Snyder DJ, Agathis AZ, Shamapant N, **Yang JY**, Pai A, Mazumdar M, Poor H. Pre-hospital antiplatelet medication use on COVID-19 disease severity. Heart & Lung 2021;50(5):618-621. DOI: https://doi.org/10.1016/j.hrtlng.2021.04.010.

Rustgi SD, **Yang JY**, Luther S, David Y, Dixon RE, Simoes PK, Kumta NA. Anticoagulation does not increase risk of mortality or ICU admission in hospitalized COVID-19 patients with gastrointestinal bleeding: Results from a New York health system. Clinics and research in hepatology and gastroenterology. 2020;45(3):101602.

Elmunzer BJ, Spitzer RL, Foster LD, et al. Digestive Manifestations in Patients Hospitalized with Coronavirus Disease 2019. Clin Gastroenterol Hepatol. 2020; S1542-3565(20)31371-9. doi: 10.1016/j.cgh.2020.09.041.

Pasik SD, Chiu S, **Yang JY**, et al. Assess Before Rx: Reducing the Overtreatment of Asymptomatic Blood Pressure Elevation in the Inpatient Setting. J. Hosp. Med 2019,3: 151-156 doi:10.12788/jhm.3190.

**Yang JY**, Chiu S, Krouss M. Overtreatment of Asymptomatic Hypertension-Urgency Is Not an Emergency: A Teachable Moment. JAMA Intern Med. 2018;178(5):704-705.

Chowdhury, SM, Lalwani G, Zhang K, et al. Cell specific cytotoxicity and uptake of graphene nanoribbons. Biomaterials 2013, 34 (1), 283-293.


See the full list of publications [here](https://scholar.google.com/citations?user=jXa9fYQAAAAJ&hl=en).